services:
  - type: web
    name: metamorfose-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    preDeployCommand: python manage.py migrate && python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
    healthCheckPath: /healthz
